# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-22 01:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
