# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-22 02:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0002_auto_20190922_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='state',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
