# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-22 02:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0003_auto_20190922_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(default='', max_length=64),
        ),
    ]
